BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `respostas` (
	`codigo`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`descricao`	TEXT,
	`codPergunta`	INTEGER
);
CREATE TABLE IF NOT EXISTS `perguntas` (
	`codigo`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`descricao`	TEXT
);
COMMIT;
